import type { Metadata } from "next";
import StyledComponentsRegistry from "../lib/registry";
import { Barlow_Condensed, Bellefair } from "next/font/google";
import "./globals.css";

const barlowCondensed = Barlow_Condensed({ subsets: ['latin'], variable: '--font-barlow-condensed', weight: ['400', '700'] });
const bellefair = Bellefair({ subsets: ['latin'], variable: '--font-bellefair', weight: '400' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${barlowCondensed.variable} ${bellefair.variable}`}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
